// context/LanguageContext.js
import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

// Translation data
const translations = {
  en: {
    // Main Screen
    'myDay': 'My Day',
    'active': 'Active',
    'addProject': 'Add Project',
    'createNewProject': 'Start your next journey',
    'settings': 'Settings',
    'data': 'Data',
    'theme': 'Theme',
    'language': 'Language',
    'notifications': 'Notifications',
    'createBackup': 'Create Backup',
    'recoverData': 'Recover Data',
    'completedProjects': 'Completed Projects',
    'noActiveProjects': 'No projects yet! 🚀',
    'startYourJourney': 'Start an amazing journey by creating your first project',
    'goBack': 'Go Back',
    'activeMilestones': 'Active Milestones',
    'entriesToday': 'Entries Today',
    'wordsToday': 'Words Today',
    'currentStreak': 'Current Streak',
    'longestStreak': 'Longest Streak',
    'wroteToday': 'Wrote Today',
    'noEntryToday': 'No Entry Today',
    'keepItUp': 'Keep it up!',
    'writeToday': 'Write today!',
    'quickStartFitness': 'Fitness',
    'quickStartLearning': 'Learning',
    'quickStartCareer': 'Career',
    'quickStartCustom': 'Create Your Own Project',
    
    // Project Screen
    'projectTitle': 'Project Title',
    'enterProjectTitle': 'Enter project title',
    'addDate': 'Add Date',
    'selectDateRange': 'Select Date Range',
    'selectStartDate': 'Select start date',
    'selectEndDate': 'Select end date',
    'dateRangeSelected': 'Date range selected',
    'clear': 'Clear',
    'week': 'Week',
    'weeks': 'Weeks',
    'month': 'Month',
    'months': 'Months',
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    
    // Active Task Menu
    'markAsIncomplete': 'Mark as Incomplete',
    'markAsComplete': 'Mark as Complete',
    'complete': 'Complete',
    
    // Journal
    'journal': 'Mood Tracker',
    'howAreYouFeeling': 'How are you feeling?',
    'writeYourThoughts': 'Write your thoughts...',
    'addPhoto': 'Add Photo',
    'addLocation': 'Add Location',
    'photo': 'Photo',
    'video': 'Video',
    'media': 'Media',
    'location': 'Location',
    'recentEntries': 'Recent Entries',
    'noMoodDataYet': 'No Mood Data Yet',
    'startWritingJournal': 'Start writing journal entries with mood tags to see your emotional journey here.',
    'entries': 'Entries',
    'activeProjects': 'Active Projects',
    'completedProjects': 'Completed Projects',
    'thisWeek': 'This Week',
    'thisMonth': 'This Month',
    'words': 'Words',
    'save': 'Save',
    'edit': 'Edit',
    'delete': 'Delete',
    'deleteJournal': 'Delete Journal?',
    'deleteJournalMessage': 'All entries and media will be permanently deleted.',
    'milestone': 'Milestone',
    'milestones': 'Milestones',
    'enterMilestoneTitle': 'Enter milestone title',
    'completedMilestones': 'Completed Milestones',
    'deleteMilestoneConfirm': 'Are you sure? 🤔',
    'deleteMilestoneMessage': 'This milestone and all its memories will be permanently deleted.',
    'journey': 'Journey',
    'moodCalendar': 'Mood Calendar',
    'attach': 'Attach',
    'detach': 'Detach',
    'selectParentMilestone': 'Select Parent Milestone',
    'noAvailableMilestones': 'No available milestones',
    'cannotReopenChild': 'Cannot Reopen',
    'parentMustBeActiveFirst': 'Parent milestone is completed. Please reopen the parent first.',
    
    // Welcome Screen
    'appName': 'Flow Journal',
    'welcomeDescription': 'Track your projects while recording your emotions. Flow Journal allows you to track your projects along with your personal experiences.',
    'getStarted': 'Get Started',
    
    // Tutorial Screen
    'tutorial': 'Tutorial',
    'createProject': 'Create Project',
    'createProjectDescription': 'Add a new project and set start-end dates',
    'addMilestones': 'Add Milestones',
    'addMilestonesDescription': 'Add step-by-step milestones to your project and track your progress',
    'emotionJournal': 'Emotion Journal',
    'emotionJournalDescription': 'Write journals and record your emotions. Transform your experiences throughout your projects into valuable memories',
    'viewProgress': 'View Progress',
    'viewProgressDescription': 'Analyze your project progress and emotional journey',
    'continue': 'Continue',
    
    // Today's Summary
    'todaysSummary': "Today's Summary",
    'howAreYouFeelingToday': 'How are you feeling today?',
    'startRecordingEmotions': 'Start recording your emotions and make sense of your day',
    'writeYourFirstJournal': 'Write your first journal',
    'greatStart': 'Great start!',
    'keepSharingEmotions': 'Keep sharing your emotions, this is very valuable',
    'writeMore': 'Write more',
    'veryActiveDay': 'Very active day!',
    'expressEmotionsBeautifully': 'You express your emotions beautifully, this is great',
    'happyDay': 'Happy day!',
    'keepRecordingPositiveEnergy': 'Keep recording this positive energy',
    'shareYourHappiness': 'Share your happiness',
    'calmDay': 'Calm day',
    'recordingPeacefulMoments': 'Recording these peaceful moments is beautiful',
    'writeYourPeace': 'Write your peace',
    'challengingDay': 'Challenging day',
    'writingEmotionsWillRelax': 'Writing your emotions will relax you',
    'expressYourEmotions': 'Express your emotions',
    'timeToRest': 'Time to rest',
    'recordingHelpsRecovery': 'Recording how you feel helps your recovery',
    'writeYourCondition': 'Write your condition',
    'normalDay': 'Normal day',
    'everyDayHasUniqueStory': 'Every day has its own unique story',
    'recordYourDay': 'Record your day',
    'goingWell': 'Going well!',
    'keepRecordingEmotions': 'Keep recording your emotions',
    
    // Mood Statement
    'todayYouFeel': 'Today you feel',
    'todayYourMoodIs': "Today you're feeling",
    'like': '',
    'viewMoreDetails': 'View more details',
    'clickMilestoneStartWriting': 'Click on a Milestone right away and start writing your journal',
    'startJournalingToday': 'Start journaling today',
    'improvingFromYesterday': '✨ You\'re feeling better than yesterday!',
    'worseningFromYesterday': '💙 Today might be a tough day, take care of yourself',
    'stableMood': '→ Consistent mood',
    'moodStreakDays': '🎯 {count} days of {mood}',
    'journalStreakDays': '🔥 You\'ve been journaling for {count} days straight!',
    'dayImprovement': '🌅 You improved during the day!',
    'dayEndFatigue': '🌙 End of day tiredness',
    'richEmotionalPalette': '🎨 Rich emotional palette',
    
    // Project Analyzer
    'projectAnalyzer': 'Project Analyzer',
    'overallStatistics': 'Overall Statistics',
    'projectPerformance': 'Project Performance',
    'moodAnalysis': 'Mood Analysis',
    'activityTimeline': 'Activity Timeline',
    'totalProjects': 'Total Projects',
    'journalEntries': 'Journal Entries',
    'completionRate': 'Completion Rate',
    'efficiency': 'Efficiency',
    'risk': 'Risk',
    'totalDuration': 'Total Duration',
    'elapsedTime': 'Elapsed Time',
    'expectedProgress': 'Expected Progress',
    'days': 'Days',
    'activeDays': 'Active Days',
    'avgDailyActivity': 'Avg Daily Activity',
    'noMoodData': 'No mood data available',
    'projectStatistics': 'Project Statistics',
    'highRiskDescription': 'Project is significantly behind schedule',
    'mediumRiskDescription': 'Project needs attention to stay on track',
    'lowRiskDescription': 'Project is performing well',
    'riskLevelHigh': 'High Risk',
    'riskLevelMedium': 'Medium Risk',
    'riskLevelLow': 'Low Risk',
    'close': 'Close',
    'todayMoodHappy': 'Today your mood is good',
    'todayMoodExcited': 'Today you feel energetic and excited',
    'todayMoodGrateful': 'Today you feel grateful and appreciative',
    'todayMoodHopeful': 'Today you feel hopeful and optimistic',
    'todayMoodProud': 'Today you feel proud and accomplished',
    'todayMoodRelieved': 'Today you feel relieved and at peace',
    'todayMoodMotivated': 'Today you feel motivated and determined',
    'todayMoodPeaceful': 'Today you feel peaceful and calm',
    'todayMoodContent': 'Today you feel content and satisfied',
    'todayMoodConfident': 'Today you feel confident and self-assured',
    'todayMoodSad': 'Today you feel a bit down',
    'todayMoodAngry': 'Today you feel frustrated and angry',
    'todayMoodTired': 'Today you feel a bit exhausted',
    'todayMoodFrustrated': 'Today you feel frustrated and stuck',
    'todayMoodAnxious': 'Today you feel anxious and worried',
    'todayMoodOverwhelmed': 'Today you feel overwhelmed and stressed',
    'todayMoodLonely': 'Today you feel a bit lonely',
    'todayMoodConfused': 'Today you feel confused and uncertain',
    'todayMoodDisappointed': 'Today you feel disappointed and let down',
    'todayMoodWorried': 'Today you feel worried and concerned',
    'todayMoodBored': 'Today you feel bored and restless',
    'todayMoodStressed': 'Today you feel stressed and tense',
    'todayMoodExhausted': 'Today you feel completely exhausted',
    'todayMoodCalm': 'Today you feel calm and serene',
    'todayMoodCurious': 'Today you feel curious and interested',
    'todayMoodNostalgic': 'Today you feel nostalgic and reflective',
    'todayMoodSurprised': 'Today you feel surprised and intrigued',
    'todayMoodFocused': 'Today you feel focused and concentrated',
    'todayMoodNeutral': 'Today you feel neutral and balanced',
    
    // Project Progress
    'noProjectOnThisDate': 'No project on this date',
    'noActiveProjectOnSelectedDate': 'No active project on selected date.\nWould you like to create a new project?',
    
    // Completed Projects
    'projectJournal': 'Project Journal',
    'projectJournals': 'Project Journals',
    'projectJourney': 'Project Journal',
    'startDocumentingProjectJourney': 'Start documenting your project journey',
    'noJournals': 'No Journals',
    'noJournalEntries': 'This project has no journal entries',
    'noCompletedProjects': 'No Completed Projects',
    
    // Journal Detail
    'location': 'Location',
    
    // Permissions
    'permissionRequired': 'Permission Required',
    'locationPermissionMessage': 'Location permission is required to add your location to the journal. Please grant permission in settings.',
    'galleryPermissionMessage': 'Gallery access permission is required to add photos. Please grant permission in settings.',
    
    // Add Milestone Modal
    'enterMilestoneTitle': 'Enter milestone title...',
    
    'resetAIFeedback': 'Reset AI Feedback',
    'resetAIFeedbackDescription': 'This will reset the AI feedback system and allow it to show again on next app start. Continue?',
    'reset': 'Reset',
    'success': 'Success',
    'aiFeedbackResetSuccess': 'AI feedback has been reset! It will show on next app start.',
    'aiFeedbackResetError': 'Failed to reset AI feedback. Please try again.',
    
    // Card
    'untitled': 'Untitled',
    
    // MileStone
    'deleteMilestoneConfirm': 'Are you sure? Deleted Milestone cannot be recovered',
    
    // Theme Toggle
    'switchToLightTheme': 'Switch to light theme',
    'switchToDarkTheme': 'Switch to dark theme',
    'lightMode': 'Light Mode',
    'darkMode': 'Dark Mode',
    
    // Completed Project Card
    'completed': 'Completed',
    
    // Moods
    'happy': 'Happy',
    'excited': 'Excited',
    'tired': 'Tired',
    'sad': 'Sad',
    'angry': 'Angry',
    'frustrated': 'Frustrated',
    'anxious': 'Anxious',
    'grateful': 'Grateful',
    'hopeful': 'Hopeful',
    'proud': 'Proud',
    'calm': 'Calm',
    'overwhelmed': 'Overwhelmed',
    'natural': 'Natural',
    'neutral': 'Neutral',
    
    'journalTime': 'Journal Time!',
    'howAboutRecording': 'How about recording your experiences and emotions today?',
    'howWasYourDay': 'How was your day? Share your thoughts!',
    'whatMadeYouHappy': 'What made you happy today?',
    'timeForJournaling': 'Time for journaling! Record your story.',
    'didYouLearn': 'Did you learn anything new today?',
    'perfectTime': 'Perfect time to record your feelings and thoughts!',
    'summarizeYourDay': 'Summarize your day and save it for future you.',
    'whatMoments': 'What moments made you smile today?',
    
    // Project Analysis
    'projectAnalysis': 'Project Analysis',
    'milestoneReminder': 'Milestone Reminder',
    'projectDeadlineApproaching': 'Project Deadline Approaching!',
    'lastDay': 'Last Day!',
    'completedToday': 'Completed Today',
    'pastDateRestriction': 'Past Date',
    'futureDateRestriction': 'Future Date',
    'cannotModifyPast': 'You cannot modify milestones in the past. You can only complete/uncomplete milestones for today.',
    'cannotModifyFuture': 'You cannot complete milestones in advance. You can only take action for today.',
    'focused': 'Focused',
    'congratulations': 'Congratulations',
    'projectCompletedToday': 'project completed today',
    'milestoneCompletedToday': 'milestone completed today',
    'wouldYouLikeToJournal': 'Would you like to journal about your experience?',
    'writeJournal': 'Write Journal',
    'later': 'Later',
    'deadlineWarning': 'Deadline Warning',
    'endsIn3Days': 'ends in 3 days. You still have time!',
    'endsTomorrow': 'ends tomorrow! Time for final touches.',
    'endsInDays': 'ends in {days} days!',
    
    // Emotional Journal Screen
    'moodTrend': 'Mood Trend',
    'projectProgress': 'Project Progress',
    'transformProjectsIntoEmotionalExperience': 'Transform Projects',
    'startYourEmotionalJourney': 'Start Your Emotional Journey',
    'captureYourFeelings': 'Capture Your Feelings',
    'documentYourProgress': 'Document Your Progress',
    'shareYourThoughts': 'Share Your Thoughts',
    'expressYourEmotions': 'Express Your Emotions',
    'recordYourExperience': 'Record Your Experience',
    'tellYourStory': 'Tell Your Story',
    'reflectOnYourJourney': 'Reflect On Your Journey',
    'learningJourneyMotivation': 'Every learning moment shapes your growth. Capture the emotions behind your progress!',
    'workProjectMotivation': 'Your professional journey deserves emotional recognition. Document how work makes you feel!',
    'healthProjectMotivation': 'Health is more than physical. Track the emotional side of your wellness journey!',
    'creativeProjectMotivation': 'Creativity flows through emotions. Let your feelings inspire your artistic process!',
    'personalGrowthMotivation': 'Personal development is deeply emotional. Record the feelings that drive your growth!',
    'complexProjectMotivation': 'Complex projects create rich emotional experiences. Don\'t let those feelings go unnoticed!',
    'simpleProjectMotivation': 'Even simple projects have emotional depth. Capture the joy in small victories!',
    'continueJournalingMotivation': 'You\'ve started documenting your journey. Keep the momentum going with emotional insights!',
    'completedProjectsJourney': 'Completed Projects Journey',
    'quickTips': 'Quick Tips',
    'emotionalJournal': 'Mood Tracker',
    'moodAnalysis': 'Mood Analysis',
    'emotionalInsights': 'Emotional Insights',
    'journeyOverview': 'Journey Overview',
    'progressTracking': 'Progress Tracking',
    'basedOnLast7Days': 'Based on your last 7 days of mood entries',
    'youHaveJournalEntries': 'You have {count} journal entries - add mood tags to track your emotional journey!',
    'youHaveMilestones': 'You have {count} milestones - start writing journal entries with mood tags!',
    'thoughtsValuable': 'Your thoughts are valuable! Adding mood tags will help you understand your emotional patterns and growth.',
    'journeyBegins': 'Every journey begins with a single step. Start documenting your progress and feelings today!',
    'moodImproving': 'Your mood is improving!',
    'moodDeclining': 'Your mood seems to be declining',
    'moodStable': 'Your mood is stable',
    
    // Motivation Messages
    'motivationHappy1': "Your happiness is your greatest asset - let it guide you to even more success!",
    'motivationHappy2': "This joy you're feeling is well-deserved. You've earned every smile!",
    'motivationHappy3': "Keep riding this wave of happiness! Your positive energy is contagious and powerful!",
    'motivationExcited1': "Your excitement is the spark that ignites great achievements! Channel this energy!",
    'motivationExcited2': "This enthusiasm is your secret weapon - use it to make amazing things happen!",
    'motivationExcited3': "Your excitement is magnetic! Let it attract more opportunities and success!",
    'motivationGrateful1': "Gratitude attracts more good things. Keep this beautiful energy flowing!",
    'motivationGrateful2': "Your appreciation mindset is creating a positive ripple effect in your life!",
    'motivationGrateful3': "This grateful heart is opening doors to even more opportunities and blessings!",
    'motivationHopeful1': "Your hope is the light that guides you through any darkness. Keep it burning bright!",
    'motivationHopeful2': "This optimism is your superpower - it's turning possibilities into realities!",
    'motivationHopeful3': "Hope is the foundation of all great achievements. You're building something amazing!",
    'motivationProud1': "You have every right to be proud. This is just the beginning of your greatness!",
    'motivationProud2': "Your pride is well-earned. Let it motivate you to reach even higher heights!",
    'motivationProud3': "This sense of accomplishment is the fuel for your next victory. Keep going!",
    'motivationMotivated1': "Your motivation is unstoppable! Keep this momentum going and achieve greatness!",
    'motivationMotivated2': "This drive is your competitive advantage - leverage it fully and succeed!",
    'motivationMotivated3': "Your determination is inspiring. Let it guide you to the success you deserve!",
    'motivationPeaceful1': "Your peace is a superpower in a chaotic world. Use it to make wise decisions!",
    'motivationPeaceful2': "This tranquility is creating space for clarity and focus. Embrace it fully!",
    'motivationPeaceful3': "Your serenity is your strength. Let it guide you through any challenge!",
    'motivationContent1': "Contentment is the highest form of success. You're exactly where you need to be!",
    'motivationContent2': "This satisfaction is the foundation for even greater achievements ahead!",
    'motivationContent3': "Your contentment is a sign of wisdom. You've found the perfect balance!",
    'motivationConfident1': "Your confidence is magnetic! It's attracting success and opportunities to you!",
    'motivationConfident2': "This self-belief is your greatest asset. Trust it and watch miracles happen!",
    'motivationConfident3': "Confidence is the key to unlocking your full potential. You've got this!",
    'motivationSad1': "It's okay to feel this way. Your feelings are valid and this too shall pass!",
    'motivationSad2': "This sadness is just making room for even greater joy ahead. You're stronger than you know!",
    'motivationSad3': "Every cloud has a silver lining. Your breakthrough is coming - stay strong!",
    'motivationAngry1': "Your anger shows you care deeply. Channel this passion into positive action!",
    'motivationAngry2': "This frustration is temporary, but your strength is permanent. Keep pushing forward!",
    'motivationAngry3': "Anger can be a powerful motivator. Use it to fuel your determination to succeed!",
    'motivationTired1': "Rest is not giving up, it's preparing for the next victory! Listen to your body!",
    'motivationTired2': "Even the strongest warriors need to rest. You're still winning - just recharge!",
    'motivationTired3': "Your body is asking for care. Take a break and come back even stronger!",
    'motivationFrustrated1': "Frustration is just success in disguise. You're closer than you think!",
    'motivationFrustrated2': "This challenge is making you stronger. Every expert was once a beginner!",
    'motivationFrustrated3': "Your frustration shows you're pushing your limits. That's where growth happens!",
    'motivationAnxious1': "Breathe deeply. You've overcome challenges before, and you will again!",
    'motivationAnxious2': "Your anxiety is just your mind preparing for success. Trust the process!",
    'motivationAnxious3': "This feeling is temporary, but your strength is permanent. You've got this!",
    'motivationOverwhelmed1': "Break it down into smaller steps. You've got this, one piece at a time!",
    'motivationOverwhelmed2': "Overwhelm is just excitement in disguise. You're capable of amazing things!",
    'motivationOverwhelmed3': "Remember: you don't have to do everything at once. Progress, not perfection!",
    'motivationLonely1': "Your solitude is a gift. Use this time to connect with your inner strength!",
    'motivationLonely2': "This loneliness is temporary. You're building resilience and self-reliance!",
    'motivationLonely3': "Sometimes we need to be alone to discover how strong we really are!",
    'motivationConfused1': "Confusion is the beginning of wisdom. You're about to discover something amazing!",
    'motivationConfused2': "This uncertainty is just the universe preparing you for clarity. Trust the process!",
    'motivationConfused3': "Every breakthrough starts with confusion. You're exactly where you need to be!",
    'motivationDisappointed1': "Disappointment is just a detour, not a dead end. Your success story continues!",
    'motivationDisappointed2': "This setback is setting you up for an even greater comeback. Stay strong!",
    'motivationDisappointed3': "Your disappointment shows you have high standards. That's a sign of greatness!",
    'motivationWorried1': "Worry is just your mind trying to protect you. You're stronger than your fears!",
    'motivationWorried2': "This concern shows you care deeply. Channel that care into positive action!",
    'motivationWorried3': "Your worries are temporary, but your ability to overcome them is permanent!",
    'motivationBored1': "Boredom is the birthplace of creativity. Use this time to explore new possibilities!",
    'motivationBored2': "This restlessness is a sign that you're ready for your next big adventure!",
    'motivationBored3': "When you're bored, you're actually ready to discover something amazing!",
    'motivationStressed1': "Stress is just your body preparing for success. You're stronger than you think!",
    'motivationStressed2': "This pressure is creating diamonds. You're being forged into something incredible!",
    'motivationStressed3': "Your stress shows you're pushing boundaries. That's where breakthroughs happen!",
    'motivationExhausted1': "Exhaustion is a sign of hard work. You're building something meaningful!",
    'motivationExhausted2': "This tiredness shows you've been giving your all. Rest and come back stronger!",
    'motivationExhausted3': "Even the strongest need to recharge. You're still winning - just take a break!",
    'motivationCalm1': "Your calmness is a superpower in a chaotic world. Use it wisely and succeed!",
    'motivationCalm2': "This peaceful energy is creating space for clarity and focus. Embrace it!",
    'motivationCalm3': "Your serenity is your strength. Let it guide you to make wise decisions!",
    'motivationCurious1': "Your curiosity is the key to unlocking new possibilities! Keep exploring!",
    'motivationCurious2': "This sense of wonder is what drives innovation. You're on the right path!",
    'motivationCurious3': "Your questions are leading you to amazing discoveries. Stay curious!",
    'motivationNostalgic1': "Your nostalgia shows you have beautiful memories. Create even more amazing ones!",
    'motivationNostalgic2': "This fondness for the past is fueling your appreciation for the present!",
    'motivationNostalgic3': "Your memories are treasures. Use them to build an even brighter future!",
    'motivationSurprised1': "Your surprise shows you're open to new experiences. That's where magic happens!",
    'motivationSurprised2': "This sense of wonder is keeping you young at heart. Embrace every surprise!",
    'motivationSurprised3': "Your openness to surprises is your greatest asset. Keep expecting the unexpected!",
    'motivationFocused1': "Your focus is laser-sharp! This concentration is your path to success!",
    'motivationFocused2': "This deep focus is creating something amazing. Keep your eyes on the prize!",
    'motivationFocused3': "Your concentration is a superpower. Use it to achieve your biggest dreams!",
    'motivationNeutral1': "Steady progress is still progress. You're exactly where you need to be!",
    'motivationNeutral2': "Consistency is the mother of mastery. Keep going and watch the magic happen!",
    'motivationNeutral3': "Your steady approach is building something beautiful. Trust the process!",
    'motivationDefault1': "You're exactly where you need to be right now. Trust the journey!",
    'motivationDefault2': "Every step you take is bringing you closer to your goals. Keep going!",
    'motivationDefault3': "Your progress is real and meaningful. You're building something amazing!",
    'projectStrongestImpact': 'Your "{project}" project has the strongest emotional impact on you.',
    'projectImpact': 'Project Impact',
    'progressStatus': 'Progress Status',
    
    // Calendar and Date Picker
    'selectDate': 'Select Date',
    'selectStartDate': 'Select Start Date',
    'selectEndDate': 'Select End Date',
    'selectDeadline': 'Select Deadline',
    'datePicker': 'Date Picker',
    'timePicker': 'Time Picker',
    'selectTime': 'Select Time',
    'confirmDate': 'Confirm Date',
    'confirmTime': 'Confirm Time',
    
    // Project Emotional Progress Messages
    'projectHappy': 'This project is a joyful experience for you!',
    'projectExcited': 'This project fills you with excitement and energy!',
    'projectGrateful': 'This project makes you feel grateful and appreciative!',
    'projectHopeful': 'This project fills you with hope and optimism!',
    'projectProud': 'This project makes you feel proud of your achievements!',
    'projectRelieved': 'This project brings you relief and peace of mind!',
    'projectMotivated': 'This project keeps you highly motivated and driven!',
    'projectPeaceful': 'This project brings you inner peace and tranquility!',
    'projectContent': 'This project makes you feel content and satisfied!',
    'projectConfident': 'This project boosts your confidence and self-belief!',
    'projectSad': 'This project is making you feel sad and downhearted',
    'projectAngry': 'This project is frustrating and angering you',
    'projectTired': 'This project is exhausting and draining your energy',
    'projectFrustrated': 'This project is proving to be frustrating for you',
    'projectAnxious': 'This project is causing you anxiety and worry',
    'projectOverwhelmed': 'This project feels overwhelming and too much to handle',
    'projectLonely': 'This project makes you feel isolated and alone',
    'projectConfused': 'This project is confusing and unclear to you',
    'projectDisappointed': 'This project is disappointing and not meeting your expectations',
    'projectWorried': 'This project is causing you worry and concern',
    'projectBored': 'This project feels boring and unengaging to you',
    'projectStressed': 'This project is stressing you out and causing tension',
    'projectExhausted': 'This project is leaving you feeling completely exhausted',
    'projectCalm': 'This project is a calm and peaceful experience for you',
    'projectCurious': 'This project sparks your curiosity and keeps you interested',
    'projectNostalgic': 'This project brings back fond memories and nostalgia',
    'projectSurprised': 'This project continues to surprise and intrigue you',
    'projectFocused': 'This project keeps you focused and concentrated',
    'projectNeutral': 'This project is progressing at a steady, neutral pace',
    'projectDefault': 'This project is progressing steadily',
    
    // Completed Project Emotional Progress Messages (Past Tense)
    'completedProjectHappy': 'This project was a joyful and fulfilling experience for you!',
    'completedProjectExcited': 'This project filled you with excitement and energy throughout!',
    'completedProjectGrateful': 'This project made you feel grateful and appreciative!',
    'completedProjectHopeful': 'This project filled you with hope and optimism!',
    'completedProjectProud': 'This project made you feel proud of your achievements!',
    'completedProjectRelieved': 'This project brought you relief and peace of mind!',
    'completedProjectMotivated': 'This project kept you highly motivated and driven!',
    'completedProjectPeaceful': 'This project brought you inner peace and tranquility!',
    'completedProjectContent': 'This project made you feel content and satisfied!',
    'completedProjectConfident': 'This project boosted your confidence and self-belief!',
    'completedProjectSad': 'This project was challenging and made you feel downhearted',
    'completedProjectAngry': 'This project was frustrating and angering for you',
    'completedProjectTired': 'This project was exhausting and drained your energy',
    'completedProjectFrustrated': 'This project proved to be frustrating for you',
    'completedProjectAnxious': 'This project caused you anxiety and worry',
    'completedProjectOverwhelmed': 'This project felt overwhelming and too much to handle',
    'completedProjectLonely': 'This project made you feel isolated and alone',
    'completedProjectConfused': 'This project was confusing and unclear to you',
    'completedProjectDisappointed': 'This project was disappointing and didn\'t meet your expectations',
    'completedProjectWorried': 'This project caused you worry and concern',
    'completedProjectBored': 'This project felt boring and unengaging to you',
    'completedProjectStressed': 'This project stressed you out and caused tension',
    'completedProjectExhausted': 'This project left you feeling completely exhausted',
    'completedProjectCalm': 'This project was a calm and peaceful experience for you',
    'completedProjectCurious': 'This project sparked your curiosity and kept you interested',
    'completedProjectNostalgic': 'This project brought back fond memories and nostalgia',
    'completedProjectSurprised': 'This project continued to surprise and intrigue you',
    'completedProjectFocused': 'This project kept you focused and concentrated',
    'completedProjectNeutral': 'This project progressed at a steady, neutral pace',
    'completedProjectDefault': 'This project was completed successfully',
    
    // Quick Tips and Recommendations
    'personalizedRecommendation': 'Personalized Recommendation',
    'journalMore': 'Journal More',
    'journalMoreMessage': 'Try to write in your journal more frequently to get better insights into your emotional patterns.',
    'emotionalDiversity': 'Emotional Diversity',
    'emotionalDiversityMessage': 'Consider exploring different activities to experience a wider range of emotions.',
    'keepDoingHappy': 'Keep doing what makes you happy! Consider sharing your positive energy with others.',
    'happinessContagious': 'Your happiness is contagious! Use this positive momentum to tackle new challenges.',
    'joyWellDeserved': 'This joy is well-deserved. Consider setting new goals to maintain this positive energy.',
    'channelExcitement': 'Channel this excitement into new projects and opportunities!',
    'enthusiasmPowerful': 'Your enthusiasm is powerful - use it to inspire others around you.',
    'energyPerfect': 'This energy is perfect for taking on bigger challenges and goals.',
    'bodyAskingRest': 'Your body is asking for rest. Consider taking a break or reducing your workload.',
    'prioritizeSelfCare': 'Prioritize self-care and ensure you\'re getting enough sleep and relaxation.',
    'reassessWorkLife': 'This tiredness might indicate you need to reassess your work-life balance.',
    'okayToFeel': 'It\'s okay to feel this way. Consider talking to someone you trust or seeking support.',
    'sadnessTemporary': 'This sadness might be temporary. Focus on small, positive activities each day.',
    'considerCausingSadness': 'Consider what might be causing this sadness and take steps to address it.',
    'anxietyManageable': 'Anxiety is manageable. Try deep breathing exercises or mindfulness practices.',
    'breakDownTasks': 'Consider breaking down overwhelming tasks into smaller, manageable steps.',
    'listenAnxiety': 'Your anxiety might be telling you something important - listen to it with compassion.',
    'frustrationSignalsGrowth': 'Frustration often signals growth. You\'re pushing your boundaries - that\'s positive!',
    'identifyFrustration': 'Try to identify what\'s causing the frustration and address it systematically.',
    'changeApproach': 'This feeling might indicate you need to change your approach or seek help.',
    'calmnessSuperpower': 'Your calmness is a superpower! Use this peaceful energy to make wise decisions.',
    'tranquilityPerfect': 'This tranquility is perfect for reflection and planning your next steps.',
    'serenityValuable': 'Your serenity is valuable - consider how to maintain this peaceful state.',
    'motivationStrong': 'Your motivation is strong! Use this drive to tackle your most important goals.',
    'determinationAdvantage': 'This determination is your competitive advantage - leverage it fully.',
    'motivationInspiring': 'Your motivation is inspiring - consider how to sustain this energy long-term.',
    'continueTracking': 'Continue tracking your emotions to better understand your patterns.',
    'setSmallGoals': 'Consider setting small, achievable goals to maintain your progress.',
    'emotionalAwareness': 'Your emotional awareness is growing - keep up the great work!',
    
    // Notification Settings
    'notificationSettings': 'Notification Settings',
    'dailyReminder': 'Daily Reminder',
    'dailyJournalingReminders': 'Daily journaling reminders',
    'subscriptionSuccess': 'Success',
    'subscribedToDailyReminders': 'You have subscribed to daily reminders!\n\nNotifications will be delivered via PythonAnywhere + FCM.',
    'unsubscribedFromDailyReminders': 'You have unsubscribed from daily reminders.',
    
    // MyDay Screen
    'lastDay': 'Last Day',
    'overdue1Day': '1 Day Overdue',
    'overdueDays': '{days} Days Overdue',
    'addMilestone': 'Milestone',
    'addJournal': 'Journal',
    'addProject': 'Add Project',
    
    // Common
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'ok': 'OK',
    'yes': 'Yes',
    'no': 'No',
    'close': 'Close',
    'back': 'Back',
    'next': 'Next',
    'previous': 'Previous',
    'done': 'Done',
    'continue': 'Continue',
    'skip': 'Skip',
    'retry': 'Retry',
    'refresh': 'Refresh',
    'search': 'Search',
    'filter': 'Filter',
    'sort': 'Sort',
    'view': 'View',
    'hide': 'Hide',
    'show': 'Show',
    'more': 'More',
    'less': 'Less',
    'all': 'All',
    'none': 'None',
    'select': 'Select',
    'selected': 'Selected',
    'unselected': 'Unselected',
    'enabled': 'Enabled',
    'disabled': 'Disabled',
    'on': 'On',
    'off': 'Off',
    'active': 'Active',
    'inactive': 'Inactive',
    'online': 'Online',
    'offline': 'Offline',
    'connected': 'Connected',
    'disconnected': 'Disconnected',
    'available': 'Available',
    'unavailable': 'Unavailable',
    'public': 'Public',
    'private': 'Private',
    'draft': 'Draft',
    'published': 'Published',
    'archived': 'Archived',
    'deleted': 'Deleted',
    'restored': 'Restored',
    'updated': 'Updated',
    'created': 'Created',
    'modified': 'Modified',
    'saved': 'Saved',
    'unsaved': 'Unsaved',
    'synchronized': 'Synchronized',
    'pending': 'Pending',
    'processing': 'Processing',
    'completed': 'Completed',
    'failed': 'Failed',
    'cancelled': 'Cancelled',
    'expired': 'Expired',
    'valid': 'Valid',
    'invalid': 'Invalid',
    'required': 'Required',
    'optional': 'Optional',
    'recommended': 'Recommended',
    'notRecommended': 'Not Recommended',
    'important': 'Important',
    'urgent': 'Urgent',
    'normal': 'Normal',
    'low': 'Low',
    'medium': 'Medium',
    'high': 'High',
    'critical': 'Critical',
    'info': 'Info',
    'warning': 'Warning',
    'debug': 'Debug',
    'verbose': 'Verbose',
    'minimal': 'Minimal',
    'detailed': 'Detailed',
    'summary': 'Summary',
    'full': 'Full',
    'partial': 'Partial',
    'complete': 'Complete',
    'incomplete': 'Incomplete',
    'empty': 'Empty',
    'full': 'Full',
    'new': 'New',
    'old': 'Old',
    'recent': 'Recent',
    'latest': 'Latest',
    'earliest': 'Earliest',
    'first': 'First',
    'last': 'Last',
    'beginning': 'Beginning',
    'end': 'End',
    'start': 'Start',
    'stop': 'Stop',
    'pause': 'Pause',
    'resume': 'Resume',
    'restart': 'Restart',
    'reset': 'Reset',
    'clear': 'Clear',
    'clean': 'Clean',
    'dirty': 'Dirty',
    'fresh': 'Fresh',
    'stale': 'Stale',
    'current': 'Current',
    'previous': 'Previous',
    'next': 'Next',
    'upcoming': 'Upcoming',
    'past': 'Past',
    'future': 'Future',
    'present': 'Present',
    'today': 'Today',
    'yesterday': 'Yesterday',
    'tomorrow': 'Tomorrow',
    'thisWeek': 'This Week',
    'lastWeek': 'Last Week',
    'nextWeek': 'Next Week',
    'thisMonth': 'This Month',
    'lastMonth': 'Last Month',
    'nextMonth': 'Next Month',
    'thisYear': 'This Year',
    'lastYear': 'Last Year',
    'nextYear': 'Next Year',
    'morning': 'Morning',
    'afternoon': 'Afternoon',
    'evening': 'Evening',
    'night': 'Night',
    'dawn': 'Dawn',
    'dusk': 'Dusk',
    'midnight': 'Midnight',
    'noon': 'Noon',
    'am': 'AM',
    'pm': 'PM',
    'monday': 'Monday',
    'tuesday': 'Tuesday',
    'wednesday': 'Wednesday',
    'thursday': 'Thursday',
    'friday': 'Friday',
    'saturday': 'Saturday',
    'sunday': 'Sunday',
    'dayAbbreviations': ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
    'january': 'January',
    'february': 'February',
    'march': 'March',
    'april': 'April',
    'may': 'May',
    'june': 'June',
    'july': 'July',
    'august': 'August',
    'september': 'September',
    'october': 'October',
    'november': 'November',
    'december': 'December'
  },
  
  tr: {
    // Main Screen
    'myDay': 'Günüm',
    'active': 'Aktif',
    'addProject': 'Proje Ekle',
    'createNewProject': 'Yeni yolculuğunuza başlayın',
    'settings': 'Ayarlar',
    'data': 'Veri',
    'theme': 'Tema',
    'language': 'Dil',
    'notifications': 'Bildirimler',
    'createBackup': 'Yedek Oluştur',
    'recoverData': 'Veri Kurtar',
    'completedProjects': 'Tamamlanan Projeler',
    'noActiveProjects': 'Henüz hiçbir proje yok! 🚀',
    'startYourJourney': 'İlk projeni oluşturarak harika bir yolculuğa başla',
  'goBack': 'Geri Dön',
  'activeMilestones': 'Aktif Kilometre Taşları',
  'entriesToday': 'Bugünkü Girişler',
  'wordsToday': 'Bugünkü Kelimeler',
  'currentStreak': 'Mevcut Seri',
  'longestStreak': 'En Uzun Seri',
  'wroteToday': 'Bugün Yazıldı',
  'noEntryToday': 'Bugün Giriş Yok',
  'keepItUp': 'Aynen Devam!',
  'writeToday': 'Bugün yazmayı unutma!',
    'quickStartFitness': 'Fitness',
    'quickStartLearning': 'Öğrenim',
    'quickStartCareer': 'Kariyer',
    'quickStartCustom': 'Kendi Projeni Oluştur',
    
    // Project Screen
    'projectTitle': 'Proje Başlığı',
    'enterProjectTitle': 'Proje başlığını girin',
    'addDate': 'Tarih Ekle',
    'selectDateRange': 'Tarih Aralığı Seç',
    'selectStartDate': 'Başlangıç tarihi seçin',
    'selectEndDate': 'Bitiş tarihi seçin',
    'dateRangeSelected': 'Tarih aralığı seçildi',
    'clear': 'Temizle',
    'week': 'Hafta',
    'weeks': 'Hafta',
    'month': 'Ay',
    'months': 'Ay',
    'cancel': 'İptal',
    'confirm': 'Onayla',
    
    // Active Task Menu
    'markAsIncomplete': 'Tamamlanmadı Olarak İşaretle',
    'markAsComplete': 'Tamamlandı Olarak İşaretle',
    'complete': 'Tamamla',
    
    // Journal
    'journal': 'Mood Tracker',
    'howAreYouFeeling': 'Nasıl hissediyorsun?',
    'writeYourThoughts': 'Düşüncelerini yaz...',
    'addPhoto': 'Fotoğraf Ekle',
    'addLocation': 'Konum Ekle',
    'photo': 'Fotoğraf',
    'video': 'Video',
    'media': 'Medya',
    'location': 'Konum',
    'recentEntries': 'Günlükler',
    'noMoodDataYet': 'Henüz Mood Verisi Yok',
    'startWritingJournal': 'Duygusal yolculuğunu burada görmek için mood etiketleriyle günlük girişleri yazmaya başla.',
    'entries': 'Girişler',
    'activeProjects': 'Aktif Projeler',
    'completedProjects': 'Tamamlanan Projeler',
    'thisWeek': 'Bu Hafta',
    'thisMonth': 'Bu Ay',
    'words': 'Kelime',
    'save': 'Kaydet',
    'edit': 'Düzenle',
    'delete': 'Sil',
    'deleteJournal': 'Günlüğü Sil?',
    'deleteJournalMessage': 'Tüm girişler ve medya kalıcı olarak silinecek.',
    'milestone': 'Görev',
    'milestones': 'Görevler',
    'enterMilestoneTitle': 'Görev başlığını girin',
    'completedMilestones': 'Tamamlanan Görevler',
    'deleteMilestoneConfirm': 'Emin misin? 🤔',
    'deleteMilestoneMessage': 'Bu görev ve tüm anıları kalıcı olarak silinecek.',
    'journey': 'Günlük',
    'moodCalendar': 'Mood Takvimi',
    'attach': 'İlişkilendir',
    'detach': 'İlişkiyi Kaldır',
    'selectParentMilestone': 'Ana Görev Seçin',
    'noAvailableMilestones': 'Uygun görev yok',
    'cannotReopenChild': 'Yeniden Açılamaz',
    'parentMustBeActiveFirst': 'Ana görev tamamlanmış durumda. Lütfen önce ana görevi yeniden açın.',
    
    // Welcome Screen
    'appName': 'Flow Journal',
    'welcomeDescription': 'Duygularını kaydederken projelerini takip et. Flow Journal, projelerini kişisel deneyimlerinle birlikte takip etmeni sağlar.',
    'getStarted': 'Başlayalım',
    
    // Tutorial Screen
    'tutorial': 'Eğitim',
    'createProject': 'Proje Oluştur',
    'createProjectDescription': 'Yeni bir proje ekle ve başlangıç-bitiş tarihlerini belirle',
    'addMilestones': 'Kilometre Taşları Ekle',
    'addMilestonesDescription': 'Projene adım adım kilometre taşları ekle ve ilerlemeni takip et',
    'emotionJournal': 'Duygusal Günlük',
    'emotionJournalDescription': 'Günlük yaz ve duygularını kaydet. Projelerin boyunca deneyimlerini değerli anılara dönüştür',
    'viewProgress': 'İlerlemeyi Görüntüle',
    'viewProgressDescription': 'Proje ilerlemeni ve duygusal yolculuğunu analiz et',
    'continue': 'Devam Et',
    
    // Today's Summary
    'todaysSummary': "Günün Özeti",
    'howAreYouFeelingToday': 'Bugün nasıl hissediyorsun?',
    'startRecordingEmotions': 'Duygularını kaydetmeye başla ve gününü anlamlandır',
    'writeYourFirstJournal': 'İlk günlüğünü yaz',
    'greatStart': 'Harika başlangıç!',
    'keepSharingEmotions': 'Duygularını paylaşmaya devam et, bu çok değerli',
    'writeMore': 'Daha fazla yaz',
    'veryActiveDay': 'Çok aktif bir gün!',
    'expressEmotionsBeautifully': 'Duygularını güzel bir şekilde ifade ediyorsun, bu harika',
    'happyDay': 'Mutlu gün!',
    'keepRecordingPositiveEnergy': 'Bu pozitif enerjiyi kaydetmeye devam et',
    'shareYourHappiness': 'Mutluluğunu paylaş',
    'calmDay': 'Sakin gün',
    'recordingPeacefulMoments': 'Bu huzurlu anları kaydetmek güzel',
    'writeYourPeace': 'Huzurunu yaz',
    'challengingDay': 'Zorlu gün',
    'writingEmotionsWillRelax': 'Duygularını yazmak seni rahatlatacak',
    'expressYourEmotions': 'Duygularını ifade et',
    'timeToRest': 'Dinlenme zamanı',
    'recordingHelpsRecovery': 'Nasıl hissettiğini kaydetmek iyileşmene yardımcı olur',
    'writeYourCondition': 'Durumunu yaz',
    'normalDay': 'Normal gün',
    'everyDayHasUniqueStory': 'Her günün kendine özgü bir hikayesi var',
    'recordYourDay': 'Gününü kaydet',
    'goingWell': 'İyi gidiyor!',
    'keepRecordingEmotions': 'Duygularını kaydetmeye devam et',
    
    // Mood Statement
    'todayYouFeel': 'Bugün',
    'todayYourMoodIs': 'Bugün moodunuz biraz',
    'like': 'gibi',
    'viewMoreDetails': 'Daha fazla detay görüntüle',
    'clickMilestoneStartWriting': 'Hemen bir Kilometre Taşına tıklayın ve günlüğünüzü yazmaya başlayın',
    'startJournalingToday': 'Bugünü kaydetmeye başlayın',
    'improvingFromYesterday': '✨ Dünden daha iyi hissediyorsun!',
    'worseningFromYesterday': '💙 Bugün zor bir gün olabilir, kendine iyi bak',
    'stableMood': '→ Tutarlı bir ruh hali',
    'moodStreakDays': '🎯 {count} gündür {mood}',
    'journalStreakDays': '🔥 {count} gün üst üste journal yazıyorsun!',
    'dayImprovement': '🌅 Gün içinde iyileştin!',
    'dayEndFatigue': '🌙 Gün sonu yorgunluğu',
    'richEmotionalPalette': '🎨 Zengin bir duygu paleti',
    
    // Project Analyzer
    'projectAnalyzer': 'Proje Analizörü',
    'overallStatistics': 'Genel İstatistikler',
    'projectPerformance': 'Proje Performansı',
    'moodAnalysis': 'Duygu Analizi',
    'activityTimeline': 'Aktivite Zaman Çizelgesi',
    'totalProjects': 'Toplam Proje',
    'journalEntries': 'Günlük Kayıtları',
    'completionRate': 'Tamamlanma Oranı',
    'efficiency': 'Verimlilik',
    'risk': 'Risk',
    'totalDuration': 'Toplam Süre',
    'elapsedTime': 'Geçen Süre',
    'expectedProgress': 'Beklenen İlerleme',
    'days': 'Gün',
    'activeDays': 'Aktif Günler',
    'avgDailyActivity': 'Günlük Ortalama Aktivite',
    'noMoodData': 'Duygu verisi mevcut değil',
    'projectStatistics': 'Proje İstatistikleri',
    'highRiskDescription': 'Proje önemli ölçüde programın gerisinde',
    'mediumRiskDescription': 'Proje plana uygun ilerlemek için dikkat gerektiriyor',
    'lowRiskDescription': 'Proje iyi performans gösteriyor',
    'riskLevelHigh': 'Yüksek Risk',
    'riskLevelMedium': 'Orta Risk',
    'riskLevelLow': 'Düşük Risk',
    'close': 'Kapat',
    'todayMoodHappy': 'Bugün modunuz iyi',
    'todayMoodExcited': 'Bugün enerjik ve heyecanlı hissediyorsunuz',
    'todayMoodGrateful': 'Bugün minnettar ve takdir edici hissediyorsunuz',
    'todayMoodHopeful': 'Bugün umutlu ve iyimser hissediyorsunuz',
    'todayMoodProud': 'Bugün gururlu ve başarılı hissediyorsunuz',
    'todayMoodRelieved': 'Bugün rahatlamış ve huzurlu hissediyorsunuz',
    'todayMoodMotivated': 'Bugün motive ve kararlı hissediyorsunuz',
    'todayMoodPeaceful': 'Bugün huzurlu ve sakin hissediyorsunuz',
    'todayMoodContent': 'Bugün memnun ve tatmin hissediyorsunuz',
    'todayMoodConfident': 'Bugün kendinden emin ve güvenli hissediyorsunuz',
    'todayMoodSad': 'Bugün biraz üzgün hissediyorsunuz',
    'todayMoodAngry': 'Bugün sinirli ve kızgın hissediyorsunuz',
    'todayMoodTired': 'Bugün biraz tükenmiş hissediyorsunuz',
    'todayMoodFrustrated': 'Bugün hayal kırıklığına uğramış ve takılmış hissediyorsunuz',
    'todayMoodAnxious': 'Bugün endişeli ve kaygılı hissediyorsunuz',
    'todayMoodOverwhelmed': 'Bugün bunalmış ve stresli hissediyorsunuz',
    'todayMoodLonely': 'Bugün biraz yalnız hissediyorsunuz',
    'todayMoodConfused': 'Bugün karışık ve belirsiz hissediyorsunuz',
    'todayMoodDisappointed': 'Bugün hayal kırıklığına uğramış ve üzgün hissediyorsunuz',
    'todayMoodWorried': 'Bugün endişeli ve kaygılı hissediyorsunuz',
    'todayMoodBored': 'Bugün sıkılmış ve huzursuz hissediyorsunuz',
    'todayMoodStressed': 'Bugün stresli ve gergin hissediyorsunuz',
    'todayMoodExhausted': 'Bugün tamamen tükenmiş hissediyorsunuz',
    'todayMoodCalm': 'Bugün sakin ve huzurlu hissediyorsunuz',
    'todayMoodCurious': 'Bugün meraklı ve ilgili hissediyorsunuz',
    'todayMoodNostalgic': 'Bugün nostaljik ve düşünceli hissediyorsunuz',
    'todayMoodSurprised': 'Bugün şaşırmış ve ilgili hissediyorsunuz',
    'todayMoodFocused': 'Bugün odaklı ve konsantre hissediyorsunuz',
    'todayMoodNeutral': 'Bugün nötr ve dengeli hissediyorsunuz',
    
    // Project Progress
    'noProjectOnThisDate': 'Bu tarihte proje yok',
    'noActiveProjectOnSelectedDate': 'Seçilen tarihte aktif proje yok.\nYeni bir proje oluşturmak ister misiniz?',
    
    // Completed Projects
    'projectJournal': 'Proje Günlüğü',
    'projectJournals': 'Proje Günlükleri',
    'projectJourney': 'Proje Günlüğü',
    'startDocumentingProjectJourney': 'Proje yolculuğunu belgelemeye başla',
    'noJournals': 'Günlük Yok',
    'noJournalEntries': 'Bu projenin günlük girişi yok',
    'noCompletedProjects': 'Tamamlanan Proje Yok',
    
    // Journal Detail
    'location': 'Konum',
    
    // Permissions
    'permissionRequired': 'İzin Gerekli',
    'locationPermissionMessage': 'Konumunuzu eklemek için konum izni gerekli. Lütfen ayarlardan izin verin.',
    'galleryPermissionMessage': 'Fotoğraf eklemek için galeri erişim izni gerekli. Lütfen ayarlardan izin verin.',
    
    // Add Milestone Modal
    'enterMilestoneTitle': 'Kilometre taşı başlığını girin...',
    
    'resetAIFeedback': 'AI Geri Bildirimini Sıfırla',
    'resetAIFeedbackDescription': 'Bu, AI geri bildirim sistemini sıfırlayacak ve bir sonraki uygulama başlatıldığında tekrar göstermesine izin verecek. Devam edilsin mi?',
    'reset': 'Sıfırla',
    'success': 'Başarılı',
    'aiFeedbackResetSuccess': 'AI geri bildirimi sıfırlandı! Bir sonraki uygulama başlatıldığında gösterilecek.',
    'aiFeedbackResetError': 'AI geri bildirimi sıfırlanamadı. Lütfen tekrar deneyin.',
    
    // Card
    'untitled': 'Başlıksız',
    
    // MileStone
    'deleteMilestoneConfirm': 'Emin misiniz? Silinen Kilometre Taşı geri alınamaz',
    
    // Theme Toggle
    'switchToLightTheme': 'Açık temaya geç',
    'switchToDarkTheme': 'Koyu temaya geç',
    'lightMode': 'Açık Mod',
    'darkMode': 'Koyu Mod',
    
    // Completed Project Card
    'completed': 'Tamamlandı',
    
    // Moods
    'happy': 'Mutlu',
    'excited': 'Heyecanlı',
    'tired': 'Yorgun',
    'sad': 'Üzgün',
    'angry': 'Kızgın',
    'frustrated': 'Sinirli',
    'anxious': 'Endişeli',
    'grateful': 'Müteşekkir',
    'hopeful': 'Umutlu',
    'proud': 'Gururlu',
    'calm': 'Sakin',
    'overwhelmed': 'Bunalmış',
    'natural': 'Doğal',
    'neutral': 'Nötr',
    
    'journalTime': 'Günlük Zamanı!',
    'howAboutRecording': 'Bugünkü deneyimlerini ve duygularını kaydetmeye ne dersin?',
    'howWasYourDay': 'Günün nasıldı? Düşüncelerini paylaş!',
    'whatMadeYouHappy': 'Bugün seni ne mutlu etti?',
    'timeForJournaling': 'Günlük yazma zamanı! Hikayeni kaydet.',
    'didYouLearn': 'Bugün yeni bir şey öğrendin mi?',
    'perfectTime': 'Duygularını ve düşüncelerini kaydetmek için mükemmel zaman!',
    'summarizeYourDay': 'Gününü özetle ve gelecekteki sen için kaydet.',
    'whatMoments': 'Bugün seni gülümseten anlar nelerdi?',
    
    // Project Analysis
    'projectAnalysis': 'Proje Analizi',
    'milestoneReminder': 'Kilometre Taşı Hatırlatıcısı',
    'projectDeadlineApproaching': 'Proje Son Tarihi Yaklaşıyor!',
    'lastDay': 'Son Gün!',
    'completedToday': 'Bugün Tamamlandı',
    'pastDateRestriction': 'Geçmiş Tarih',
    'futureDateRestriction': 'Gelecek Tarih',
    'cannotModifyPast': 'Geçmişteki milestone\'ları değiştiremezsiniz. Sadece bugün için complete/uncomplete yapabilirsiniz.',
    'cannotModifyFuture': 'Gelecekteki milestone\'ları şimdiden complete edemezsiniz. Sadece bugün için işlem yapabilirsiniz.',
    'focused': 'Odaklanıldı',
    'congratulations': 'Tebrikler',
    'projectCompletedToday': 'projesini bugün tamamladınız',
    'milestoneCompletedToday': 'adımını bugün tamamladınız',
    'wouldYouLikeToJournal': 'Deneyimlerinizi yazmak ister misiniz?',
    'writeJournal': 'Günlük Yaz',
    'later': 'Sonra',
    'deadlineWarning': 'Son Tarih Uyarısı',
    'endsIn3Days': '3 gün içinde bitiyor. Hala zamanın var!',
    'endsTomorrow': 'yarın bitiyor! Son dokunuşlar için zaman.',
    'endsInDays': '{days} gün içinde bitiyor!',
    
    // Emotional Journal Screen
    'moodTrend': 'Mood Trendi',
    'projectProgress': 'Proje İlerlemesi',
    'transformProjectsIntoEmotionalExperience': 'Projeleri Dönüştür',
    'startYourEmotionalJourney': 'Duygusal Yolculuğunu Başlat',
    'captureYourFeelings': 'Duygularını Yakala',
    'documentYourProgress': 'İlerlemeni Belgele',
    'shareYourThoughts': 'Düşüncelerini Paylaş',
    'expressYourEmotions': 'Duygularını İfade Et',
    'recordYourExperience': 'Deneyimini Kaydet',
    'tellYourStory': 'Hikayeni Anlat',
    'reflectOnYourJourney': 'Yolculuğunu Yansıt',
    'learningJourneyMotivation': 'Her öğrenme anı gelişimini şekillendirir. İlerlemenin arkasındaki duyguları yakala!',
    'workProjectMotivation': 'Profesyonel yolculuğun duygusal tanınmayı hak ediyor. İşin seni nasıl hissettirdiğini belgele!',
    'healthProjectMotivation': 'Sağlık sadece fiziksel değil. Wellness yolculuğunun duygusal yanını takip et!',
    'creativeProjectMotivation': 'Yaratıcılık duygulardan akar. Duyguların sanatsal sürecini ilham etsin!',
    'personalGrowthMotivation': 'Kişisel gelişim derinden duygusaldır. Büyümeni tetikleyen hisleri kaydet!',
    'complexProjectMotivation': 'Karmaşık projeler zengin duygusal deneyimler yaratır. Bu hisleri fark edilmeden bırakma!',
    'simpleProjectMotivation': 'Basit projeler bile duygusal derinliğe sahiptir. Küçük zaferlerdeki sevinci yakala!',
    'continueJournalingMotivation': 'Yolculuğunu belgelemeye başladın. Duygusal içgörülerle momentumu sürdür!',
    'completedProjectsJourney': 'Tamamlanan Projeler',
    'quickTips': 'Hızlı İpuçları',
    'emotionalJournal': 'Mood Tracker',
    'moodAnalysis': 'Mood Analizi',
    'emotionalInsights': 'Duygusal İçgörüler',
    'journeyOverview': 'Genel Bakış',
    'progressTracking': 'İlerleme Takibi',
    'basedOnLast7Days': 'Son 7 günlük mood girişlerinize dayanarak',
    'youHaveJournalEntries': '{count} günlük girişiniz var - duygusal yolculuğunuzu takip etmek için mood etiketleri ekleyin!',
    'youHaveMilestones': '{count} kilometre taşınız var - mood etiketleriyle günlük girişleri yazmaya başlayın!',
    'thoughtsValuable': 'Düşünceleriniz değerli! Mood etiketleri eklemek duygusal kalıplarınızı ve gelişiminizi anlamanıza yardımcı olacak.',
    'journeyBegins': 'Her yolculuk tek bir adımla başlar. Bugün ilerlemenizi ve duygularınızı belgelemeye başlayın!',
    'moodImproving': 'Moodunuz iyileşiyor!',
    'moodDeclining': 'Moodunuz düşüyor gibi görünüyor',
    'moodStable': 'Moodunuz stabil',
    
    // Motivation Messages - Turkish
    'motivationHappy1': "Mutluluğunuz en büyük varlığınız - sizi daha da büyük başarılara yönlendirsin!",
    'motivationHappy2': "Hissettiğiniz bu sevinç hak edilmiş. Her gülümsemeyi kazandınız!",
    'motivationHappy3': "Bu mutluluk dalgasını sürmeye devam edin! Pozitif enerjiniz bulaşıcı ve güçlü!",
    'motivationExcited1': "Heyecanınız büyük başarıları ateşleyen kıvılcım! Bu enerjiyi yönlendirin!",
    'motivationExcited2': "Bu coşku sizin gizli silahınız - harika şeyler yapmak için kullanın!",
    'motivationExcited3': "Heyecanınız manyetik! Daha fazla fırsat ve başarı çeksin!",
    'motivationGrateful1': "Minnettarlık daha fazla iyi şeyi çeker. Bu güzel enerjiyi akışta tutun!",
    'motivationGrateful2': "Takdir zihniyetiniz hayatınızda pozitif dalga etkisi yaratıyor!",
    'motivationGrateful3': "Bu minnettar kalp daha fazla fırsat ve bereket kapısı açıyor!",
    'motivationHopeful1': "Umutunuz sizi her karanlıktan geçiren ışık. Parlak yanmaya devam etsin!",
    'motivationHopeful2': "Bu iyimserlik sizin süper gücünüz - imkansızlıkları gerçekliğe dönüştürüyor!",
    'motivationHopeful3': "Umut tüm büyük başarıların temelidir. Harika bir şey inşa ediyorsunuz!",
    'motivationProud1': "Gurur duymaya her hakkınız var. Bu sadece büyüklüğünüzün başlangıcı!",
    'motivationProud2': "Gururunuz hak edilmiş. Sizi daha yüksek zirvelere ulaştırmaya motive etsin!",
    'motivationProud3': "Bu başarı duygusu bir sonraki zaferinizin yakıtı. Devam edin!",
    'motivationMotivated1': "Motivasyonunuz durdurulamaz! Bu momentumu sürdürün ve büyüklük elde edin!",
    'motivationMotivated2': "Bu güç rekabet avantajınız - tam olarak kullanın ve başarın!",
    'motivationMotivated3': "Kararlılığınız ilham verici. Sizi hak ettiğiniz başarıya yönlendirsin!",
    'motivationPeaceful1': "Huzurunuz kaotik dünyada süper güç. Bilge kararlar vermek için kullanın!",
    'motivationPeaceful2': "Bu sakinlik netlik ve odak için alan yaratıyor. Tamamen kucaklayın!",
    'motivationPeaceful3': "Huzurunuz gücünüz. Sizi her zorluktan geçirsin!",
    'motivationContent1': "Memnuniyet başarının en yüksek biçimidir. Tam olmanız gereken yerde!",
    'motivationContent2': "Bu tatmin önünüzde daha büyük başarıların temelidir!",
    'motivationContent3': "Memnuniyetiniz bilgeliğin işareti. Mükemmel dengeyi buldunuz!",
    'motivationConfident1': "Özgüveniniz manyetik! Size başarı ve fırsatlar çekiyor!",
    'motivationConfident2': "Bu kendine güven en büyük varlığınız. Güvenin ve mucizeleri izleyin!",
    'motivationConfident3': "Özgüven tam potansiyelinizi açmanın anahtarı. Başaracaksınız!",
    'motivationSad1': "Böyle hissetmeniz normal. Duygularınız geçerli ve bu da geçecek!",
    'motivationSad2': "Bu üzüntü sadece önünüzde daha büyük sevinç için yer açıyor. Sandığınızdan daha güçlüsünüz!",
    'motivationSad3': "Her bulutun gümüş kenarı vardır. Atılımınız geliyor - güçlü kalın!",
    'motivationAngry1': "Öfkeniz derinden önemsediğinizi gösteriyor. Bu tutkuyu pozitif eyleme yönlendirin!",
    'motivationAngry2': "Bu hayal kırıklığı geçici, ama gücünüz kalıcı. İleri itmeye devam edin!",
    'motivationAngry3': "Öfke güçlü bir motivatör olabilir. Başarı kararlılığınızı beslemek için kullanın!",
    'motivationTired1': "Dinlenmek pes etmek değil, bir sonraki zafer için hazırlanmaktır! Vücudunuzu dinleyin!",
    'motivationTired2': "En güçlü savaşçılar bile dinlenmeye ihtiyaç duyar. Hala kazanıyorsunuz - sadece şarj olun!",
    'motivationTired3': "Vücudunuz bakım istiyor. Mola verin ve daha güçlü geri dönün!",
    'motivationFrustrated1': "Hayal kırıklığı sadece kılık değiştirmiş başarıdır. Sandığınızdan daha yakınsınız!",
    'motivationFrustrated2': "Bu zorluk sizi güçlendiriyor. Her uzman bir zamanlar acemiydi!",
    'motivationFrustrated3': "Hayal kırıklığınız sınırlarınızı zorladığınızı gösteriyor. Büyüme orada olur!",
    'motivationAnxious1': "Derin nefes alın. Daha önce zorlukları aştınız, yine aşacaksınız!",
    'motivationAnxious2': "Endişeniz sadece zihninizin başarı için hazırlanması. Sürece güvenin!",
    'motivationAnxious3': "Bu his geçici, ama gücünüz kalıcı. Başaracaksınız!",
    'motivationOverwhelmed1': "Daha küçük adımlara bölün. Başaracaksınız, bir parça bir parça!",
    'motivationOverwhelmed2': "Bunalmışlık sadece kılık değiştirmiş heyecandır. Harika şeyler yapabilirsiniz!",
    'motivationOverwhelmed3': "Unutmayın: her şeyi aynı anda yapmak zorunda değilsiniz. Mükemmellik değil, ilerleme!",
    'motivationLonely1': "Yalnızlığınız bir hediye. Bu zamanı iç gücünüzle bağlantı kurmak için kullanın!",
    'motivationLonely2': "Bu yalnızlık geçici. Dayanıklılık ve kendine güven inşa ediyorsunuz!",
    'motivationLonely3': "Bazen ne kadar güçlü olduğumuzu keşfetmek için yalnız olmamız gerekir!",
    'motivationConfused1': "Karışıklık bilgeliğin başlangıcıdır. Harika bir şey keşfetmek üzeresiniz!",
    'motivationConfused2': "Bu belirsizlik sadece evrenin sizi netlik için hazırlaması. Sürece güvenin!",
    'motivationConfused3': "Her atılım karışıklıkla başlar. Tam olmanız gereken yerde!",
    'motivationDisappointed1': "Hayal kırıklığı sadece bir sapma, çıkmaz sokak değil. Başarı hikayeniz devam ediyor!",
    'motivationDisappointed2': "Bu aksilik sizi daha büyük bir geri dönüş için hazırlıyor. Güçlü kalın!",
    'motivationDisappointed3': "Hayal kırıklığınız yüksek standartlarınız olduğunu gösteriyor. Bu büyüklüğün işareti!",
    'motivationWorried1': "Endişe sadece zihninizin sizi korumaya çalışması. Korkularınızdan daha güçlüsünüz!",
    'motivationWorried2': "Bu endişe derinden önemsediğinizi gösteriyor. Bu özeni pozitif eyleme yönlendirin!",
    'motivationWorried3': "Endişeleriniz geçici, ama onları aşma yeteneğiniz kalıcı!",
    'motivationBored1': "Sıkıntı yaratıcılığın doğum yeridir. Bu zamanı yeni olasılıkları keşfetmek için kullanın!",
    'motivationBored2': "Bu huzursuzluk bir sonraki büyük maceranıza hazır olduğunuzun işareti!",
    'motivationBored3': "Sıkıldığınızda, aslında harika bir şey keşfetmeye hazırsınız!",
    'motivationStressed1': "Stres sadece vücudunuzun başarı için hazırlanması. Sandığınızdan daha güçlüsünüz!",
    'motivationStressed2': "Bu baskı elmas yaratıyor. İnanılmaz bir şeye dönüştürülüyorsunuz!",
    'motivationStressed3': "Stresiniz sınırları zorladığınızı gösteriyor. Atılımlar orada olur!",
    'motivationExhausted1': "Bitkinlik sıkı çalışmanın işaretidir. Anlamlı bir şey inşa ediyorsunuz!",
    'motivationExhausted2': "Bu yorgunluk elinizden geleni verdiğinizi gösteriyor. Dinlenin ve daha güçlü geri dönün!",
    'motivationExhausted3': "En güçlüler bile şarj olmaya ihtiyaç duyar. Hala kazanıyorsunuz - sadece mola verin!",
    'motivationCalm1': "Sakinliğiniz kaotik dünyada süper güç. Bilgece kullanın ve başarın!",
    'motivationCalm2': "Bu huzurlu enerji netlik ve odak için alan yaratıyor. Kucaklayın!",
    'motivationCalm3': "Huzurunuz gücünüz. Bilge kararlar vermenizi sağlasın!",
    'motivationCurious1': "Merakınız yeni olasılıkları açmanın anahtarı! Keşfetmeye devam edin!",
    'motivationCurious2': "Bu merak duygusu inovasyonu yönlendiren şey. Doğru yoldasınız!",
    'motivationCurious3': "Sorularınız sizi harika keşiflere götürüyor. Meraklı kalın!",
    'motivationNostalgic1': "Nostaljiniz güzel anılarınız olduğunu gösteriyor. Daha da harika olanlarını yaratın!",
    'motivationNostalgic2': "Geçmişe olan bu sevgi şimdiki zamanı takdir etmenizi besliyor!",
    'motivationNostalgic3': "Anılarınız hazineler. Daha parlak bir gelecek inşa etmek için kullanın!",
    'motivationSurprised1': "Şaşkınlığınız yeni deneyimlere açık olduğunuzu gösteriyor. Sihir orada olur!",
    'motivationSurprised2': "Bu merak duygusu sizi genç tutuyor. Her sürprizi kucaklayın!",
    'motivationSurprised3': "Sürprizlere açıklığınız en büyük varlığınız. Beklenmedik olanı beklemeye devam edin!",
    'motivationFocused1': "Odağınız lazer keskinliğinde! Bu konsantrasyon başarınızın yolu!",
    'motivationFocused2': "Bu derin odak harika bir şey yaratıyor. Gözünüzü ödülde tutun!",
    'motivationFocused3': "Konsantrasyonunuz süper güç. En büyük hayallerinizi gerçekleştirmek için kullanın!",
    'motivationNeutral1': "Sabit ilerleme hala ilerlemedir. Tam olmanız gereken yerde!",
    'motivationNeutral2': "Tutarlılık ustalığın anasıdır. Devam edin ve sihri izleyin!",
    'motivationNeutral3': "Sabit yaklaşımınız güzel bir şey inşa ediyor. Sürece güvenin!",
    'motivationDefault1': "Şu anda tam olmanız gereken yerde. Yolculuğa güvenin!",
    'motivationDefault2': "Attığınız her adım sizi hedeflerinize yaklaştırıyor. Devam edin!",
    'motivationDefault3': "İlerlemeniz gerçek ve anlamlı. Harika bir şey inşa ediyorsunuz!",
    'projectStrongestImpact': '"{project}" projeniz sizin üzerinizde en güçlü duygusal etkiye sahip.',
    'projectImpact': 'Proje Etkisi',
    'progressStatus': 'İlerleme Durumu',
    
    // Calendar and Date Picker
    'selectDate': 'Tarih Seç',
    'selectStartDate': 'Başlangıç Tarihi Seç',
    'selectEndDate': 'Bitiş Tarihi Seç',
    'selectDeadline': 'Son Tarih Seç',
    'datePicker': 'Tarih Seçici',
    'timePicker': 'Saat Seçici',
    'selectTime': 'Saat Seç',
    'confirmDate': 'Tarihi Onayla',
    'confirmTime': 'Saati Onayla',
    
    // Project Emotional Progress Messages
    'projectHappy': 'Bu proje senin için neşeli ve keyifli bir deneyim!',
    'projectExcited': 'Bu proje seni heyecan ve enerjiyle dolduruyor!',
    'projectGrateful': 'Bu proje seni minnettar ve takdir edici hissettiriyor!',
    'projectHopeful': 'Bu proje seni umut ve iyimserlikle dolduruyor!',
    'projectProud': 'Bu proje başarılarından gurur duymanı sağlıyor!',
    'projectRelieved': 'Bu proje sana rahatlama ve huzur veriyor!',
    'projectMotivated': 'Bu proje seni yüksek motivasyonla ve kararlılıkla tutuyor!',
    'projectPeaceful': 'Bu proje sana iç huzur ve sakinlik getiriyor!',
    'projectContent': 'Bu proje seni memnun ve tatmin olmuş hissettiriyor!',
    'projectConfident': 'Bu proje özgüvenini ve kendine olan inancını artırıyor!',
    'projectSad': 'Bu proje seni üzgün ve kırgın hissettiriyor',
    'projectAngry': 'Bu proje seni sinirlendiriyor ve kızdırıyor',
    'projectTired': 'Bu proje seni yoruyor ve enerjini tüketiyor',
    'projectFrustrated': 'Bu proje senin için sinir bozucu oluyor',
    'projectAnxious': 'Bu proje sana endişe ve kaygı veriyor',
    'projectOverwhelmed': 'Bu proje çok fazla ve başa çıkılamaz geliyor',
    'projectLonely': 'Bu proje seni yalnız ve izole hissettiriyor',
    'projectConfused': 'Bu proje seni karıştırıyor ve belirsiz geliyor',
    'projectDisappointed': 'Bu proje hayal kırıklığı yaratıyor ve beklentilerini karşılamıyor',
    'projectWorried': 'Bu proje sana endişe ve kaygı veriyor',
    'projectBored': 'Bu proje sıkıcı ve ilgisiz geliyor',
    'projectStressed': 'Bu proje seni strese sokuyor ve gerginlik yaratıyor',
    'projectExhausted': 'Bu proje seni tamamen bitkin hissettiriyor',
    'projectCalm': 'Bu proje senin için sakin ve huzurlu bir deneyim',
    'projectCurious': 'Bu proje merakını uyandırıyor ve ilgini çekiyor',
    'projectNostalgic': 'Bu proje güzel anıları ve nostaljiyi geri getiriyor',
    'projectSurprised': 'Bu proje seni şaşırtmaya ve ilgini çekmeye devam ediyor',
    'projectFocused': 'Bu proje seni odaklı ve konsantre tutuyor',
    'projectNeutral': 'Bu proje sabit ve nötr bir tempoda ilerliyor',
    'projectDefault': 'Bu proje istikrarlı bir şekilde ilerliyor',
    
    // Completed Project Emotional Progress Messages (Past Tense)
    'completedProjectHappy': 'Bu proje senin için neşeli ve tatmin edici bir deneyimdi!',
    'completedProjectExcited': 'Bu proje seni baştan sona heyecan ve enerjiyle doldurdu!',
    'completedProjectGrateful': 'Bu proje seni minnettar ve takdir edici hissettirdi!',
    'completedProjectHopeful': 'Bu proje seni umut ve iyimserlikle doldurdu!',
    'completedProjectProud': 'Bu proje başarılarından gurur duymanı sağladı!',
    'completedProjectRelieved': 'Bu proje sana rahatlama ve huzur getirdi!',
    'completedProjectMotivated': 'Bu proje seni yüksek motivasyonla ve kararlılıkla tuttu!',
    'completedProjectPeaceful': 'Bu proje sana iç huzur ve sakinlik getirdi!',
    'completedProjectContent': 'Bu proje seni memnun ve tatmin olmuş hissettirdi!',
    'completedProjectConfident': 'Bu proje özgüvenini ve kendine olan inancını artırdı!',
    'completedProjectSad': 'Bu proje zorlu bir deneyimdi ve seni üzgün hissettirdi',
    'completedProjectAngry': 'Bu proje senin için sinir bozucu ve kızdırıcıydı',
    'completedProjectTired': 'Bu proje yorucuydu ve enerjini tüketti',
    'completedProjectFrustrated': 'Bu proje senin için sinir bozucu oldu',
    'completedProjectAnxious': 'Bu proje sana endişe ve kaygı verdi',
    'completedProjectOverwhelmed': 'Bu proje çok fazla ve başa çıkılamaz geldi',
    'completedProjectLonely': 'Bu proje seni yalnız ve izole hissettirdi',
    'completedProjectConfused': 'Bu proje karışıktı ve belirsizdi',
    'completedProjectDisappointed': 'Bu proje hayal kırıklığı yarattı ve beklentilerini karşılamadı',
    'completedProjectWorried': 'Bu proje sana endişe ve kaygı verdi',
    'completedProjectBored': 'Bu proje sıkıcı ve ilgisiz geldi',
    'completedProjectStressed': 'Bu proje seni strese soktu ve gerginlik yarattı',
    'completedProjectExhausted': 'Bu proje seni tamamen bitkin hissettirdi',
    'completedProjectCalm': 'Bu proje senin için sakin ve huzurlu bir deneyimdi',
    'completedProjectCurious': 'Bu proje merakını uyandırdı ve ilgini çekti',
    'completedProjectNostalgic': 'Bu proje güzel anıları ve nostaljiyi geri getirdi',
    'completedProjectSurprised': 'Bu proje seni şaşırtmaya ve ilgini çekmeye devam etti',
    'completedProjectFocused': 'Bu proje seni odaklı ve konsantre tuttu',
    'completedProjectNeutral': 'Bu proje sabit ve nötr bir tempoda ilerledi',
    'completedProjectDefault': 'Bu proje başarıyla tamamlandı',
    
    // Quick Tips and Recommendations
    'personalizedRecommendation': 'Kişiselleştirilmiş Öneri',
    'journalMore': 'Daha Fazla Günlük Yaz',
    'journalMoreMessage': 'Duygusal kalıplarınızı daha iyi anlamak için günlüğünüzü daha sık yazmayı deneyin.',
    'emotionalDiversity': 'Duygusal Çeşitlilik',
    'emotionalDiversityMessage': 'Daha geniş bir duygu yelpazesi yaşamak için farklı aktiviteleri keşfetmeyi düşünün.',
    'keepDoingHappy': 'Seni mutlu eden şeyleri yapmaya devam et! Bu pozitif enerjini başkalarıyla paylaşmayı düşün.',
    'happinessContagious': 'Mutluluğun bulaşıcı! Bu pozitif momentumu yeni zorluklarla başa çıkmak için kullan.',
    'joyWellDeserved': 'Bu sevinç hak edilmiş. Bu pozitif enerjiyi korumak için yeni hedefler belirlemeyi düşün.',
    'channelExcitement': 'Bu heyecanı yeni projelere ve fırsatlara yönlendir!',
    'enthusiasmPowerful': 'Coşkun çok güçlü - bunu çevrendeki insanları ilhamlandırmak için kullan.',
    'energyPerfect': 'Bu enerji daha büyük zorluklar ve hedefler için mükemmel.',
    'bodyAskingRest': 'Vücudun dinlenme istiyor. Mola vermeyi veya iş yükünü azaltmayı düşün.',
    'prioritizeSelfCare': 'Kendine bakımı öncelikle ve yeterince uyku ve rahatlama aldığından emin ol.',
    'reassessWorkLife': 'Bu yorgunluk iş-yaşam dengesini yeniden değerlendirmen gerektiğini gösterebilir.',
    'okayToFeel': 'Böyle hissetmen normal. Güvendiğin biriyle konuşmayı veya destek almayı düşün.',
    'sadnessTemporary': 'Bu üzüntü geçici olabilir. Her gün küçük, pozitif aktivitelere odaklan.',
    'considerCausingSadness': 'Bu üzüntüye neyin sebep olabileceğini düşün ve bunu ele almak için adımlar at.',
    'anxietyManageable': 'Endişe yönetilebilir. Derin nefes egzersizleri veya farkındalık pratikleri dene.',
    'breakDownTasks': 'Büyük görevleri daha küçük, yönetilebilir adımlara bölmeyi düşün.',
    'listenAnxiety': 'Endişen sana önemli bir şey söylüyor olabilir - onu şefkatle dinle.',
    'frustrationSignalsGrowth': 'Hayal kırıklığı genellikle büyüme işaretidir. Sınırlarını zorluyorsun - bu pozitif!',
    'identifyFrustration': 'Hayal kırıklığına neyin sebep olduğunu belirlemeye çalış ve bunu sistematik olarak ele al.',
    'changeApproach': 'Bu his yaklaşımını değiştirmen veya yardım araman gerektiğini gösterebilir.',
    'calmnessSuperpower': 'Sakinliğin bir süper güç! Bu huzurlu enerjiyi bilge kararlar vermek için kullan.',
    'tranquilityPerfect': 'Bu huzur düşünmek ve bir sonraki adımlarını planlamak için mükemmel.',
    'serenityValuable': 'Huzurun değerli - bu huzurlu durumu nasıl koruyacağını düşün.',
    'motivationStrong': 'Motivasyonun güçlü! Bu gücü en önemli hedeflerine ulaşmak için kullan.',
    'determinationAdvantage': 'Bu kararlılık rekabet avantajın - bunu tam olarak kullan.',
    'motivationInspiring': 'Motivasyonun ilham verici - bu enerjiyi uzun vadede nasıl sürdüreceğini düşün.',
    'continueTracking': 'Duygusal kalıplarını daha iyi anlamak için duygularını takip etmeye devam et.',
    'setSmallGoals': 'İlerlemeni korumak için küçük, ulaşılabilir hedefler belirlemeyi düşün.',
    'emotionalAwareness': 'Duygusal farkındalığın gelişiyor - harika iş çıkarıyorsun!',
    
    // Notification Settings
    'notificationSettings': 'Bildirim Ayarları',
    'dailyReminder': 'Günlük Hatırlatma',
    'dailyJournalingReminders': 'Günlük yazma hatırlatmaları',
    'subscriptionSuccess': 'Başarılı',
    'subscribedToDailyReminders': 'Günlük hatırlatmalara abone oldunuz!\n\nBildirimler PythonAnywhere + FCM ile gelecek.',
    'unsubscribedFromDailyReminders': 'Günlük hatırlatmalardan abonelik iptal edildi.',
    
    // MyDay Screen
    'lastDay': 'Son Gün',
    'overdue1Day': '1 Gün Gecikme',
    'overdueDays': '{days} Gün Gecikme',
    'addMilestone': 'Görev',
    'addJournal': 'Günlük',
    'addProject': 'Proje Ekle',
    
    // Common
    'loading': 'Yükleniyor...',
    'error': 'Hata',
    'success': 'Başarılı',
    'ok': 'Tamam',
    'yes': 'Evet',
    'no': 'Hayır',
    'close': 'Kapat',
    'back': 'Geri',
    'next': 'İleri',
    'previous': 'Önceki',
    'done': 'Tamamlandı',
    'continue': 'Devam Et',
    'skip': 'Atla',
    'retry': 'Tekrar Dene',
    'refresh': 'Yenile',
    'search': 'Ara',
    'filter': 'Filtrele',
    'sort': 'Sırala',
    'view': 'Görüntüle',
    'hide': 'Gizle',
    'show': 'Göster',
    'more': 'Daha Fazla',
    'less': 'Daha Az',
    'all': 'Tümü',
    'none': 'Hiçbiri',
    'select': 'Seç',
    'selected': 'Seçili',
    'unselected': 'Seçilmemiş',
    'enabled': 'Etkin',
    'disabled': 'Devre Dışı',
    'on': 'Açık',
    'off': 'Kapalı',
    'active': 'Aktif',
    'inactive': 'Pasif',
    'online': 'Çevrimiçi',
    'offline': 'Çevrimdışı',
    'connected': 'Bağlı',
    'disconnected': 'Bağlantısız',
    'available': 'Mevcut',
    'unavailable': 'Mevcut Değil',
    'public': 'Genel',
    'private': 'Özel',
    'draft': 'Taslak',
    'published': 'Yayınlandı',
    'archived': 'Arşivlendi',
    'deleted': 'Silindi',
    'restored': 'Geri Yüklendi',
    'updated': 'Güncellendi',
    'created': 'Oluşturuldu',
    'modified': 'Değiştirildi',
    'saved': 'Kaydedildi',
    'unsaved': 'Kaydedilmedi',
    'synchronized': 'Senkronize Edildi',
    'pending': 'Beklemede',
    'processing': 'İşleniyor',
    'completed': 'Tamamlandı',
    'failed': 'Başarısız',
    'cancelled': 'İptal Edildi',
    'expired': 'Süresi Doldu',
    'valid': 'Geçerli',
    'invalid': 'Geçersiz',
    'required': 'Gerekli',
    'optional': 'İsteğe Bağlı',
    'recommended': 'Önerilen',
    'notRecommended': 'Önerilmeyen',
    'important': 'Önemli',
    'urgent': 'Acil',
    'normal': 'Normal',
    'low': 'Düşük',
    'medium': 'Orta',
    'high': 'Yüksek',
    'critical': 'Kritik',
    'info': 'Bilgi',
    'warning': 'Uyarı',
    'debug': 'Hata Ayıklama',
    'verbose': 'Ayrıntılı',
    'minimal': 'Minimal',
    'detailed': 'Detaylı',
    'summary': 'Özet',
    'full': 'Tam',
    'partial': 'Kısmi',
    'complete': 'Tamamlanmış',
    'incomplete': 'Tamamlanmamış',
    'empty': 'Boş',
    'full': 'Dolu',
    'new': 'Yeni',
    'old': 'Eski',
    'recent': 'Son',
    'latest': 'En Son',
    'earliest': 'En Erken',
    'first': 'İlk',
    'last': 'Son',
    'beginning': 'Başlangıç',
    'end': 'Son',
    'start': 'Başlat',
    'stop': 'Durdur',
    'pause': 'Duraklat',
    'resume': 'Devam Et',
    'restart': 'Yeniden Başlat',
    'reset': 'Sıfırla',
    'clear': 'Temizle',
    'clean': 'Temiz',
    'dirty': 'Kirli',
    'fresh': 'Taze',
    'stale': 'Bayat',
    'current': 'Mevcut',
    'previous': 'Önceki',
    'next': 'Sonraki',
    'upcoming': 'Yaklaşan',
    'past': 'Geçmiş',
    'future': 'Gelecek',
    'present': 'Şimdi',
    'today': 'Bugün',
    'yesterday': 'Dün',
    'tomorrow': 'Yarın',
    'thisWeek': 'Bu Hafta',
    'lastWeek': 'Geçen Hafta',
    'nextWeek': 'Gelecek Hafta',
    'thisMonth': 'Bu Ay',
    'lastMonth': 'Geçen Ay',
    'nextMonth': 'Gelecek Ay',
    'thisYear': 'Bu Yıl',
    'lastYear': 'Geçen Yıl',
    'nextYear': 'Gelecek Yıl',
    'morning': 'Sabah',
    'afternoon': 'Öğleden Sonra',
    'evening': 'Akşam',
    'night': 'Gece',
    'dawn': 'Şafak',
    'dusk': 'Alacakaranlık',
    'midnight': 'Gece Yarısı',
    'noon': 'Öğle',
    'am': 'ÖÖ',
    'pm': 'ÖS',
    'monday': 'Pazartesi',
    'tuesday': 'Salı',
    'wednesday': 'Çarşamba',
    'thursday': 'Perşembe',
    'friday': 'Cuma',
    'saturday': 'Cumartesi',
    'sunday': 'Pazar',
    'dayAbbreviations': ['Pa', 'Pt', 'Sa', 'Ça', 'Pe', 'Cu', 'Ct'],
    'january': 'Ocak',
    'february': 'Şubat',
    'march': 'Mart',
    'april': 'Nisan',
    'may': 'Mayıs',
    'june': 'Haziran',
    'july': 'Temmuz',
    'august': 'Ağustos',
    'september': 'Eylül',
    'october': 'Ekim',
    'november': 'Kasım',
    'december': 'Aralık'
  }
};

// Language Context
const LanguageContext = createContext();

// Language Provider
export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');
  const [isLoading, setIsLoading] = useState(true);

  // Load language from storage
  useEffect(() => {
    const loadLanguage = async () => {
      try {
        const savedLanguage = await AsyncStorage.getItem('app_language');
        if (savedLanguage && translations[savedLanguage]) {
          setLanguage(savedLanguage);
        }
      } catch (error) {
        console.error('Language loading error:', error);
      } finally {
        setIsLoading(false);
      }
    };

    loadLanguage();
  }, []);

  // Change language
  const changeLanguage = async (newLanguage) => {
    try {
      if (translations[newLanguage]) {
        setLanguage(newLanguage);
        await AsyncStorage.setItem('app_language', newLanguage);
      }
    } catch (error) {
      console.error('Language change error:', error);
    }
  };

  // Get translation
  const t = (key, params = {}) => {
    let translation = translations[language][key] || key;
    
    // Replace parameters
    Object.keys(params).forEach(param => {
      translation = translation.replace(`{${param}}`, params[param]);
    });
    
    return translation;
  };

  // Get current language info
  const getLanguageInfo = () => {
    return {
      code: language,
      name: language === 'en' ? 'English' : 'Türkçe',
      nativeName: language === 'en' ? 'English' : 'Türkçe',
      flag: language === 'en' ? '🇺🇸' : '🇹🇷'
    };
  };

  const value = {
    language,
    changeLanguage,
    t,
    getLanguageInfo,
    isLoading
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

// Hook to use language context
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default LanguageContext;
